# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIm9jpp_A65We4LeGl9SBWnYlakU8ENX
"""

import streemlit as st

st.title("Primera aplicacion en streemlit")
st.header("Este es un encabezado")
st.subheader("Este es un subtitulo")
st.write("Esta es una introduccion a Streamlit, donde exploraremos  como hacer aplicaciones interactivas ")